#!/usr/bin/perl

#/usr/local/sbin/conf-ivite-call
use Log::Lite qw(logrotate logmode logpath log);

logrotate("month");           #autocut logfile every month.
logmode("log");               #log in file (Default)
logpath("/var/log/callfiles");    #defined where log files stored

#$file = "/tmp/call/".$ARGV[1].".call";

$BIND = $ARGV[0];
$confname = $ARGV[1];
$invite_num = $ARGV[2];
$ConfBrArg = $ARGV[3];

#opt/obit
#my $cmd = "cd /tmp/call/&&touch ".$ARGV[1].".call";
my $cmd = "cd /opt/obit/call/&&touch ".$confname."-".$invite_num.".call";

log("conf-call-files",$cmd);
system ($cmd);
#$file = "/tmp/call/".$ARGV[1].".call";
$file = "/opt/obit/call/".$confname."-".$invite_num.".call";

#$BIND = $ARGV[0];
#$confname = $ARGV[1];
#$invite_num = $ARGV[2];
#$ConfBrArg = $ARGV[3];

log("conf-call-files","FILES".$file." BIND ".$BIND."confname ".$confname." invite_num :"."$ConfBrArg: ".$ConfBrArg."/n");

open(FILE, "> $file");
print FILE "Channel: SIP/".$BIND."+".$invite_num."\n";
print FILE "CallerID: ".$confname."\n";
print FILE "MaxRetries: 1\n";
print FILE "RetryTime: 30\n";
print FILE "WaitTime: 60\n";
print FILE "Application: ConfBridge\n";
print FILE "Data: ".$confname." \n";
close(FILE);
system ("mv /opt/obit/call/".$confname."-".$invite_num.".call /var/spool/asterisk/outgoing");
