#!/bin/bash
umask 122

CONF="$1"

count=0
CFG=''

CFG="${CONF}"
[ "`dirname $CONF`" == "/pbx/hw" ] && CONF=`basename $CONF` && CFG="/pbx/hw/${CFG}"
count=`ls -1 "${CFG}" 2>/dev/null | wc -l`

if [ "$CFG" == "" ] || [ $count -eq 0 ]; then
  CFG1=`find /pbx/hw/ -type f -name "*${CONF}*" | egrep -v '^$'`
  count=`echo -n ${CFG} | wc -l`
  if [ ${count} -gt 1 ]; then
    echo "  Ambiguous \"$1\":"
    echo "${CFG1}"
    exit 0
  fi
  [ ${count} -eq 1 ] && CFG="${CFG1}"

  if [ ${count} -eq 0 ]; then
    count=`grep -Rli "${CONF}" /pbx/hw/ | wc -l`
    if [ ${count} -gt 1 ]; then
      echo "  Multiple \"${CONF}\" inside configurations:"
      grep -Rli "${CONF}" /pbx/hw/
      exit 0
    fi
    [ ${count} -eq 1 ] && CFG=`grep -Rli "${CONF}" /pbx/hw/`
  fi
fi

CONF="${CFG}"
#echo ${CONF}

mt=`stat -c '%Y' "${CONF}" 2>/dev/null || echo 0`
f=`readlink -f "${CONF}" | egrep "^/pbx/hw/"`
[ $? -ne 0 ] && exit

echo `date "+%Y.%m.%d %H:%M"`" ${SUDO_UID} ${SUDO_USER}: OPEN ${f}" >> /var/log/device.log

if [ "$2" != "!" ] && [ "$2" != "!!" ]; then
  nano -kw -Y "/usr/share/nano/conf.nanorc" -o `dirname ${f}` "${CONF}"
  mt1=`stat -c '%Y' "${CONF}" 2>/dev/null || echo 0`

  if [ "$mt1" -eq "$mt" ]; then
    echo 'Config unchanged'
    exit 0
  fi
fi


f=`readlink -f "${CONF}"`
conf=`echo ${f} | egrep '^/pbx/hw/'`

cat "${conf}" | /usr/local/sbin/schema
res=$?


if [ ${res} -eq 0 ]; then
  echo "${conf} OK"
  echo `date "+%Y.%m.%d %H:%M"`" ${SUDO_UID} ${SUDO_USER}: OK ${f}" >> /var/log/device.log
else
#  cat "${conf}.err"
  echo `date "+%Y.%m.%d %H:%M"`" ${SUDO_UID} ${SUDO_USER}: ERROR [${res}] in config ${f}" >> /var/log/device.log
  exit
fi
