#!/bin/bash
umask 177

# egress PHONE [up|down]

EXT=$1
if [ "${EXT}" == "" ]; then
  echo "Usage: $0 PHONE [up|down]"
  echo "  e.g. $0 8123388838 down"
  exit
fi

if [ "$2" == "" ]; then
  # Check current status
  p=`psql -U postgres -h 192.168.5.111 -qtc "SELECT \"Exten\"||' from '||\"CID\",\"Description\" from \"Func\" where \"BIND\" is NULL and \"Exten\" = 'ALL' and \"CID\" = '$EXT';" a3 | sed -r 's/\s+/ /g'`
  if [ "${p}" != "" ]; then
    echo "EGRESS DOWN: ${p}"
  else
    p=`psql -U postgres -h 192.168.5.111 -qtc "SELECT \"NRec\",\"Channel\",\"Description\" from \"Route\" where (\"SourceLow\" = '$EXT' and \"SourceHigh\" = '$EXT') order by \"NRec\" desc;" a3 | sed -r 's/[ ]+/ /g;s/[|]/ >> channel #/'`
    [ "${p}" != "" ] && echo "EGRESS UP: ${p}"
  fi

  if [ "${p}" == "" ]; then
    echo "EGRESS UNKNOWN: No distinct route for \"${EXT}\""
  fi

  exit
fi

[ "$2" == "down" ] && del='' || del='-- '
[ "${del}" == "" ] && d='DOWN' || d='UP'

p=`psql -U postgres -h 192.168.5.111 -qtc "SELECT \"Exten\" from \"Func\" where \"Exten\" = '$EXT' and NOT(\"BIND\" is NULL);" pbx | egrep -o '[0-9]+'`
if [ $? -gt 0 ]; then
  echo "No DID found for \"$BIND\""
  exit 1
fi

(
 echo "${del}[Func ALL ${p}] ; `basename $0` \"${EXT}\""
 echo " Macro = Tones ; (fn,Timeout,NoTransfer,Limit)"
 echo " P1 = Congestion"
 echo " P2 = 60"
) | /usr/local/sbin/upsert -b 'NULL' -IDT | psql -U postgres -h 192.168.5.111 -q a3

echo "EGRESS ${d} for DID [$p]"
