#!/bin/sh
umask 177

# Group for test
gr=$1
[ -z "${gr}" ] && gr='8000'

# Exact rule, if one is needed
peers=$2
[ -z "${peers}" ] && peers=`echo "^${gr}" | head -c 3 ; echo -n '[0-9]{2}/'`

SYSADMIN="ds@miwan.me"

HOST=`/bin/hostname`
FQDN=`/bin/hostname -f`

state=0

while [ 1 = 1 ]
do
 sleep 60

 dt="/bin/date +%d.%m.%Y-%H:%M:%S"

 body=`/usr/sbin/asterisk -rx 'sip show peers' | /bin/egrep "${peers}" | /bin/grep 'OK'`
 res=$?
 if [ ${res} -ne ${state} ]; then
  if [ ${res} -ne 0 ]; then
   subj="!!!NO PHONES FOR [${gr}] GROUP!!!"
   body='*NONE*'
  else
   subj="[${gr}] GROUP OK"
  fi

cat << EOF | /usr/local/sbin/mailer -f "${HOST} <alive@${FQDN}>" -t "PBX maintainers <${SYSADMIN}>" -s "${subj}"
At [`$dt`] ${HOST}>"sip show peers" output was:
Name/username              Host             Dyn FRP_ACL Port    Status       Realtime
${body}
EOF

  state=${res}
 fi
done
