#!/bin/sh
#UserParameter=sip.8000,/usr/bin/sudo /usr/sbin/asterisk -rx 'sip show peers' | /bin/egrep '^80[0-9]{2}/' | /bin/grep 'OK' | /bin/egrep -o '^[0-9]+' | /usr/bin/wc -w
#UserParameter=ext.8000,/usr/bin/psql -U asterisk -Atqc "SELECT count(*) from \"LineStatus\" where (\"Line\" ~ '^80(0[2-9]|1[0-9]$)') and (\"Status\" in ('ANSWER','BUSY','CANCEL'))" pbx
#UserParameter=last.8000,/usr/bin/psql -U asterisk -Atqc "SELECT int8(extract('epoch' from now() - max(\"DT\"))/60) from \"LineStatus\" where (\"Line\") ~ '^80(0[2-9]|1[0-9]$)'" pbx
#UserParameter=dnd.8000,/usr/bin/psql -U asterisk -Atqc "SELECT count(*) from \"LineStatus\" where (\"Line\" ~ '^80(0[2-9]|1[0-9]$)') and (\"Status\" = 'DND')" pbx

ext=`echo "${2}" | /usr/bin/tr -dc [:digit:][:alpha:]`

case "$1" in
  'sip' )
    /usr/bin/sudo /usr/sbin/asterisk -rx 'sip show peers' | /bin/egrep "^${ext}/" | /bin/grep 'OK' | /bin/egrep -o '^[0-9]+' | /usr/bin/wc -w
    ;;
  'dnd' )
    /usr/bin/psql -U postgres -h 192.168.5.111 -Atqc "SELECT count(*) from \"LineStatus\" where (\"Line\" = '${ext}') and (\"Status\" = 'DND')" a3
    ;;
  * )
    echo ERROR
    ;;
esac
