#!/bin/sh
# Search in ldap for given attribute with wildcards
if [ -z "$2" ]; then
 ldapsearch -LLLD 'cn=ldapsearch,dc=dengionline,dc=com' -w 'ldapsearchpass19_91' -h ox.dengionline.com -x -b 'dc=dengionline,dc=com' "(|(sn=*$1*)(displayName=*$1*))" dn displayName\
  | awk '{print "echo -n \"" $1 " \"; echo -n \"" $2 " (\"; echo " $2 " | base64 -d 2>/dev/null ; echo -n \")\"; echo"}' | sh | sed 's/()//' | sed 's/ (r)//'
else
 ldapsearch -LLLD 'cn=ldapsearch,dc=dengionline,dc=com' -w 'ldapsearchpass19_91' -h ox.dengionline.com -x -b 'dc=dengionline,dc=com' "($2=*$1*)" dn $2\
  | awk '{print "echo -n \"" $1 " \"; echo -n \"" $2 " (\"; echo " $2 " | base64 -d 2>/dev/null ; echo -n \")\"; echo"}' | sh | sed 's/()//' | sed 's/ (r)//'
fi
