#!/usr/bin/perl
use strict;

my $if = $ARGV[0];
my $rate = "$ARGV[1]"."kbit";
my $tc = "/sbin/tc";

if ($if eq "")
{
 print "Interface must be defined!\n";
 exit;
}

unless ($ARGV[1] =~ m/^[\d]+$/)
{
 if (uc($ARGV[1]) eq "DOWN")
 {
 `/sbin/tc qdisc del dev $if root`;
 `/sbin/tc qdisc del dev $if ingress`;
  print "Shaper on $if DOWN.\n";
 } else
 {
  my $qdisc = `tc -s qdisc show dev $if`;
  my $filter = `$tc -s filter show dev $if parent ffff:`;
  print "Shaper on $if:\n";
  print "$qdisc\n$filter\n";
 }
} else
{
 my $burst1 = int($ARGV[1] / 128) . "kb";
 my $burst2 = int($ARGV[1] / 16) . "kb";
 print "$tc qdisc add dev $if root tbf rate $rate latency 40ms burst $burst1\n";
 `$tc qdisc add dev $if root tbf rate $rate latency 40ms burst $burst1`;
 `$tc qdisc add dev $if handle ffff: ingress`;
 `$tc filter add dev $if parent ffff: protocol ip prio 1 u32 match ip src 0.0.0.0/0 police rate $rate burst $burst2 drop flowid :1`;
 print "Shaper on $if set to $ARGV[1] kbit/s\n";
}
