#!/bin/bash
# USE THE BRAIN, LUKE!!! auto-clean, sql-executing version of card
umask 122

CONF="$1"



/usr/local/sbin/upsert -c "$1" -b "maxx" -CTSD
# -DI -C
#if [ "$3" != "delete" ]; then
#  /usr/local/sbin/upsert -c "${CONF}" -b "$BIND" -TC${SU}${DI}

#else
#  /usr/local/sbin/upsert -c "${CONF}" -b "$BIND" -dCTPSD
#fi
#res=$?

#if [ ${res} -eq 0 ]; then
#  /usr/local/sbin/conf "${sql}"
#  res=$?
#else
#  echo `date "+%Y.%m.%d %H:%M"`"${SUDO_UID} ${SUDO_USER}: ERROR [${res}] in config ${f}" >> /var/log/card.log
#  exit
#fi
#
#if [ ${res} -eq 0 ]; then
#  echo `date "+%Y.%m.%d %H:%M"`"${SUDO_UID} ${SUDO_USER}: OK ${f}" >> /var/log/card.log
#else
#  echo `date "+%Y.%m.%d %H:%M"`"${SUDO_UID} ${SUDO_USER}: ERROR [${res}] in SQL ${sql}" >> /var/log/card.log
#fi
